### ISSUE TITLE
change description

### ISSUE THREAD

**Issue by ghost** [mikeslattery/tunic#1]
this one

> Install Linux on Windows without a Live USB

isn't clear enough and you're left guessing if this is some kind of Linux subsystem for windows or similar 

I'd recommend this description:

> Install Linux on a computer that's running Windows, without a Live USB

**Comment by mikeslattery** [comment]
Thank you for the feedback.  I appreciate it.

How about?: "Install Linux on an existing Windows system, without a live USB" 
Or?: "Install Linux on a computer running Windows, without a live USB"

I want to avoid informal wording like "that's"
Anybody else have a better idea?

**Comment by Gyges88** [comment]
Nice and brief: "Install Linux from a running Windows system, without the need to boot from CD or USB."
More precise: "Install a native Linux distribution from a running Windows system, without the need to boot from CD or USB."
Even more precise: "Install a native Linux distribution (not WSL) from a running Windows system, without the need to boot from CD or USB."

**Comment by mikeslattery** [comment]
I shortened it to "Install Linux from a running Windows system, without need for a live USB."
I'll leave this ticket open until tomorrow before I close it.  Thanks for the feedback

**Comment by Gyges88** [comment]
Good choice!
However, for appearances where longer description is suitable I would suggest to consider adding another line that describes what exactly this app is and does.
Something like "After collecting necessary user data like settings and user name, this app will reboot your computer to a preconfigured Linux installer that will use this information to install Linux with your very own settings either ALONGSIDE or INSTEAD OF Windows."

**Comment by C0rn3j** [comment]
"Install Linux over or next to an existing Windows install, straight from Windows, without requiring to boot from external media like a flash drive"

Is what I'd personally go for, as there are multiple boot methods one could use, not just booting from mass storage.

**Comment by Zeustopher** [comment]
Why not something along the lines of "Install Linux as a _replacement_ for Windows, or dual-boot Linux _alongside_ Windows, right from a native Windows application"?

**Comment by mikeslattery** [comment]
Feel free to re-open this ticket if anybody wants to re-open the debate.
