### ISSUE TITLE
Did not worked on Windows XP - SP2 (32 bit)

### ISSUE THREAD

**Issue by pavangayakwad** [mikeslattery/tunic#16]
Was trying to upgrade one of my customer's Windows XP system, that lacked UEFI boot facility. Thought of using your tool to install Linux. However, the tunic.exe did not run on Windows XP Service Pack 2 system (32 bit). bummer! 

It would be great if you support legacy windows systems as well.

**Comment by mikeslattery** [comment]
I wrote the current version in PowerShell which would be nearly impossible to get working on XP.

I am in the process of a Python  rewrite which will make it possible to support XP, but it won't be easy.  Python's XP support was dropped in 2019.

Additionally, the pandemic has made it difficult for me to make much progress.

I would not expect XP 32 bit support anytime soon, if ever.    Sorry.
