### ISSUE TITLE
Tab index is messed up

### ISSUE THREAD

**Issue by C0rn3j** [mikeslattery/tunic#4]
I expect every form to get selected when pressing tab, but some are skipped.

![tab_index_tunic](https://user-images.githubusercontent.com/1641362/73789291-c690ba80-479e-11ea-8068-67ab2365495f.gif)

**Comment by mikeslattery** [comment]
Thanks for the report.
I did that on purpose.  I figured username, full name, and computer name likely wouldn't change.  I'll put them back in the tab order if that feels better.
