### ISSUE TITLE
Consider using the distro-agnostic Calamares installer instead of Ubiquity

### ISSUE THREAD

**Issue by Gyges88** [mikeslattery/tunic#5]
... for this might be easier in order to support all kinds of distros.

**Comment by mikeslattery** [comment]
I'd love to.  It will be a while before I get to it.  Debian-Installer (and the Ubiquity fork) is the primary target atm.  Each distro added has to be separately tested and possibly will require special logic.

Calamares supports the same preseed format, so adding it shouldn't be too hard.

**Comment by mikeslattery** [comment]
Tunic uses whatever installer a distro supplies.   It cannot use an arbitrary installer as it would necessarily evolve into its own distro.

Closing as this is moot.
