### ISSUE TITLE
bcdedit : the term is not recognized.

### ISSUE THREAD

**Issue by benarla** [mikeslattery/tunic#9]
Hi man, thanks for your tool. I would love to use it but i have a problem while trying to install any distro in dual boot, i get this error message on the powershell window that opens with the app. I tried to do a sfc /scannow but it doesn't solves my problem. I have a fresh windows install.

bcdedit : The term 'bcdedit' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\benji\AppData\Local\Temp\Tunic\tunic.ps1:401 char:9
+         bcdedit /export "${global:tunic_dir}\bcd-before.bak" | out-nu ...
+         ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bcdedit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

bcdedit : The term 'bcdedit' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\benji\AppData\Local\Temp\Tunic\tunic.ps1:408 char:9
+         bcdedit /delete "$osloader" /cleanup /f | out-null
+         ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bcdedit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

bcdedit : The term 'bcdedit' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\benji\AppData\Local\Temp\Tunic\tunic.ps1:410 char:18
+     $osloader = (bcdedit /copy '{bootmgr}' /d ubuntu).replace('The en ...
+                  ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bcdedit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

bcdedit : The term 'bcdedit' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\benji\AppData\Local\Temp\Tunic\tunic.ps1:411 char:5
+     bcdedit /set         "$osloader" device "partition=$efi" | out-nu ...
+     ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bcdedit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

bcdedit : The term 'bcdedit' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\benji\AppData\Local\Temp\Tunic\tunic.ps1:416 char:9
+         bcdedit /set         "$osloader" path "\EFI\BOOT\grubx64.efi" ...
+         ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bcdedit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

bcdedit : The term 'bcdedit' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\benji\AppData\Local\Temp\Tunic\tunic.ps1:418 char:5
+     bcdedit /set         "$osloader" description "Tunic Linux Install ...
+     ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bcdedit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

bcdedit : The term 'bcdedit' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\benji\AppData\Local\Temp\Tunic\tunic.ps1:419 char:5
+     bcdedit /deletevalue "$osloader" locale | out-null
+     ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bcdedit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

bcdedit : The term 'bcdedit' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\benji\AppData\Local\Temp\Tunic\tunic.ps1:420 char:5
+     bcdedit /deletevalue "$osloader" inherit | out-null
+     ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bcdedit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

bcdedit : The term 'bcdedit' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\benji\AppData\Local\Temp\Tunic\tunic.ps1:421 char:5
+     bcdedit /deletevalue "$osloader" default | out-null
+     ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bcdedit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

bcdedit : The term 'bcdedit' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\benji\AppData\Local\Temp\Tunic\tunic.ps1:422 char:5
+     bcdedit /deletevalue "$osloader" resumeobject | out-null
+     ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bcdedit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

bcdedit : The term 'bcdedit' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\benji\AppData\Local\Temp\Tunic\tunic.ps1:423 char:5
+     bcdedit /deletevalue "$osloader" displayorder | out-null
+     ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bcdedit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

bcdedit : The term 'bcdedit' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\benji\AppData\Local\Temp\Tunic\tunic.ps1:424 char:5
+     bcdedit /deletevalue "$osloader" toolsdisplayorder | out-null
+     ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bcdedit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

bcdedit : The term 'bcdedit' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\benji\AppData\Local\Temp\Tunic\tunic.ps1:425 char:5
+     bcdedit /deletevalue "$osloader" timeout | out-null
+     ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bcdedit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

bcdedit : The term 'bcdedit' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\benji\AppData\Local\Temp\Tunic\tunic.ps1:426 char:5
+     bcdedit /set '{fwbootmgr}' displayorder "$osloader" /addfirst | o ...
+     ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bcdedit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

bcdedit : The term 'bcdedit' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\benji\AppData\Local\Temp\Tunic\tunic.ps1:434 char:5
+     bcdedit /export "${global:tunic_dir}\bcd-grub.bak" | out-null
+     ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bcdedit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by benarla** [comment]
also i always get a c = a number that changes everytime and then false just under it when i open the app

**Comment by mikeslattery** [comment]
What version of Windows are you using?
Does this file exist?  `C:\Windows\System32\bcdedit.exe`

**Comment by benarla** [comment]
I'm on windows 10 pro 1909 and yes i do have this file

**Comment by mikeslattery** [comment]
If you launch from "Windows PowerShell" instead of "Windows Powershell (x86)" you shouldn't have this issue.   Or you can launch it directly from `C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe`.

#### Details

https://stackoverflow.com/questions/28040321/powershell-cant-understand-bcdedit
https://superuser.com/questions/831336/bcdedit-exe-is-not-recognized-win-8-1

bcdedit.exe is not accessible in the PATH from 32 bit Powershell, but is from 64 bit.

I will have Tunic check for this and display a pop-up warning and relaunch tunic in a separate 64 bit powershell process.

**Comment by benarla** [comment]
well nice thank you very much. I don't know how to do it so i will wait for your fix to be implemented in a release

**Comment by mikeslattery** [comment]
It will likely be released this weekend or Monday.  Or, if you don't want to wait, you can download and extract a .zip of the source and run `tunic.ps1` from powershell:
https://codeload.github.com/mikeslattery/tunic/zip/develop
